北海道:
  札幌:
    - 石山神社
    - 勝源神社
    - 江南神社
    - 札幌護国神社
    - 札幌諏訪神社
    - 
    - 
    - 
 - 
 - 
 - 
 - 
 - 
 - 
 - 
 - 
 - 
 - 
 - 
 - 
 - 
 - 
 - 

青森県:
 - 
岩手県:
 - 
秋田県:
 - 
宮城県:
 - 
山形県:
 - 
福島県:
 - 
茨城県:
 - 息栖神社
 - 御岩神社
 - 大洗磯前神社
 - 笠間稲荷神社
 - 鹿島神宮
 - 酒列磯前神社
 - 大宝八幡宮
 - 筑波山神社
 - 常磐神社
 - 一言主神社

栃木県:
 - 厳島神社 美人弁天
 - 大前神社・大前恵比寿神社
 - 蒲生神社
 - 鷲子山上神社
 - 那須温泉神社
 - 日光東照宮
 - 日光二荒山神社
 - 古峯神社

群馬県:
 - 赤城神社
 - 一之宮貫前神社
 - 冠稲荷神社
 - 上野総社神社
 - 雷電神社

埼玉県:
 - 川越熊野神社
 - 川越八幡宮
 - 川越氷川神社
 - 行田八幡神社
 - 高麗神社
 - 秩父神社
 - 鎮守氷川神社
 - 所澤神明社
 - 聖神社
 - 寳登山神社
 - 三峯神社
 - 武蔵一宮 氷川神社

千葉県:
 - 安房神社
 - 香取神宮
 - 千葉神社
 - 櫻木神社
 - 高家神社

東京都:
 - 
神奈川県:
 - 稲毛神社
 - 
 - 江島神社・江島弁財天
 - 大山阿夫利神社
 - 鎌倉宮
 - 葛原岡神社
 - 九頭竜神社本店
 - 小動神社
 - 御霊神社
 - 前鳥神社
 - 佐助稲荷神社
 - 寒川神社
 - 銭洗弁財天宇賀福神社
 - 鶴岡八幡宮
 - 鶴嶺八幡宮(淡嶋神社)
 - 富岡八幡宮
 - 西叶神社
 - 箱根神社
 - 箱根元宮
 - 走水神社
 - 東叶神社
 - 報徳二宮神社
 - 八雲神社
 - 龍口明神社

山梨県:
 - 
長野県:
 - 
新潟県:
 - 
富山県:
 - 
石川県:
 - 
福井県:
 - 
静岡県:
 - 
愛知県:
 - 熱田神宮
 - 洲崎神社
 - 若宮八幡宮
 - 愛知縣護国神社
 - 菅生神社
 - 真清田神社
岐阜県:
 - 
三重県:
 - 伊勢神宮
 - 多度大社
滋賀県:
 - 
京都府:
 - 
大阪府:
 - 
兵庫県:
 - 
奈良県:
 - 
和歌山県:
 - 
鳥取県:
 - 
島根県:
 - 
岡山県:
 - 
広島県:
 - 
山口県:
 - 
徳島県:
 - 
香川県:
 - 
愛媛県:
 - 
高知県:
 - 
福岡県:
 - 
佐賀県:
 - 
長崎県:
 - 
熊本県:
 - 
大分県:
 - 春日神社
 - 柞原八幡宮
 - 宇佐神社
 - 妻垣神社
 - 臼杵八坂神社
 - 福良天満宮
 - 金鷹山 若宮八幡社
 - 扇森稲荷神社
 - 雲八幡宮
 - 中津大神宮
 - 粟嶋社
 - 八幡朝見神社

宮崎県:
 - 
鹿児島県:
 - 
沖縄県:
 - 